safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /
url: http://localhost:4000

paginate: 1

source:      .
destination: ./_site
plugins:     ./_plugins

exclude: ['README.md']
future:      true
lsi:         true
pygments:    true
markdown:    rdiscount
permalink:   date
production: false

rdiscount:
  extensions: []
